---
title: "strings and factors"
author: "Aiying Huang"
date: "2023-10-17"
output: github_document
---

```{r}
library(rvest)
library(tidyverse)
library(p8105.datasets)
```

## Strings and regex

```{r}
string_vec = c("my", "name", "is", "jeff")

str_detect(string_vec,"jeff")

str_detect(string_vec,"e")

str_replace(string_vec,"jeff","Jeff")
```

```{r}
string_vec = c(
  "i think we all rule for participating",
  "i think i have been caught",
  "i think this will be quite fun actually",
  "it will be fun, i think"
  )

str_detect(string_vec, "i think")

str_detect(string_vec, "^i think")

str_detect(string_vec, "i think$")
```

```{r}
string_vec = c(
  "Time for a Pumpkin Spice Latte!",
  "went to the #pumpkinpatch last weekend",
  "Pumpkin Pie is obviously the best pie",
  "SMASHING PUMPKINS -- LIVE IN CONCERT!!"
  )

str_detect(string_vec,"pumpkin")

str_detect(string_vec,"Pumpkin")

str_detect(string_vec,"[Pp]umpkin")

str_detect(string_vec,"[pP]umpkin")
```

```{r}
string_vec = c(
  '7th inning stretch',
  '1st half soon to begin. Texas won the toss.',
  'she is 5 feet 4 inches tall',
  '3AM - cant sleep :('
  )

str_detect(string_vec, "^[0-9][a-zA-Z]")
```

```{r}
string_vec = c(
  'Its 7:11 in the evening',
  'want to go to 7-11?',
  'my flight is AA711',
  'NetBios: scanning ip 203.167.114.66'
  )

str_detect(string_vec, "7.11")#'.'means any character in regular expression

str_detect(string_vec, "7\\.11")#actual .(because \ can be a special character as well.)
```

```{r}
string_vec = c(
  'The CI is [2, 5]',
  ':-]',
  ':-[',
  'I found the answer on pages [6-7]'
  )

str_detect(string_vec, "\\[")
```

## Thoughts on factors

```{r}
vec_sex = factor(c("male", "male", "female", "female"))
#in alphabetical order
vec_sex
as.numeric(vec_sex)
```


What happens if i relevel...

```{r}
vec_sex = fct_relevel(vec_sex, "male")
vec_sex
as.numeric(vec_sex)
```

## NSDUH

```{r}
nsduh_url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

table_marj = 
  read_html(nsduh_url) |> 
  html_table() |> 
  first() |>
  slice(-1)
```

```{r}
data_marj = 
  table_marj |>
  select(-contains("P Value")) |>
  pivot_longer(
    -State,
    names_to = "age_year", 
    values_to = "percent") |>
  separate(age_year, into = c("age", "year"), sep = "\\(") |>
  mutate(
    year = str_replace(year, "\\)", ""),
    percent = str_replace(percent, "[a-c]$", ""),# fi not, the code would break, and I want it 
    percent = as.numeric(percent)) |>
  filter(!(State %in% c("Total U.S.", "Northeast", "Midwest", "South", "West")))
```

```{r}
data_marj |>
  filter(age == "12-17") |> 
  mutate(State = fct_relevel(State, "Texas","Ohio")) |> 
  ggplot(aes(x = State, y = percent, color = year)) + 
    geom_point() + 
    theme(axis.text.x = element_text(angle = 90, hjust = 1))#make the labels more beautiful to see
```


```{r}
data_marj |>
  filter(age == "12-17") |> 
  mutate(State = fct_reorder(State, percent)) |> # median value
  ggplot(aes(x = State, y = percent, color = year)) + 
    geom_point() + 
    theme(axis.text.x = element_text(angle = 90, hjust = 1))#make the labels more beautiful to see
```










